// <auto-generated />
namespace AssetTrackingSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_cat_genCat_subCat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_cat_genCat_subCat));
        
        string IMigrationMetadata.Id
        {
            get { return "201610241607407_adding_cat_genCat_subCat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
