// <auto-generated />
namespace AssetTrackingSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_isdeleted_flag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_isdeleted_flag));
        
        string IMigrationMetadata.Id
        {
            get { return "201610231614469_adding_isdeleted_flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
